added deletion of last line in Readme created by helm-docs

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 #
 
+OS_VERSION=$(uname -s)
+
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 YELLOW='\033[1;33m'
@@ -14,7 +16,7 @@ function info {
 }
 
 function error {
-  >&2 echo -e "[${RED}Error${NOCOLOR}] ${@}"
+  echo >&2 -e "[${RED}Error${NOCOLOR}] ${@}"
 }
 
 function warn {
@@ -22,15 +24,13 @@ function warn {
 }
 
 function check_for_update {
-  if ! command -v diff > /dev/null
-  then
+  if ! command -v diff >/dev/null; then
     info "not checking for update since diff is not installed"
     return
   fi
 
   info "Checking if hooks need to be updated"
-  if ! cmp -s $SCRIPT ./hooks/pre-commit
-  then
+  if ! cmp -s $SCRIPT ./hooks/pre-commit; then
     warn "Your commit hook is outdated please run ./install-hooks.sh again!"
     exit 1
   fi
@@ -42,8 +42,7 @@ check_for_update
 info "Executing hooks"
 
 # check if helm docs is installed
-if ! command -v helm-docs > /dev/null
-then
+if ! command -v helm-docs >/dev/null; then
   error "helm-docs is not installed"
   exit 1
 fi
@@ -52,8 +51,12 @@ fi
 
 find ./charts/ -type f -name Chart.yaml -execdir bash -c 'helm-docs 2>/dev/null' \;
 
+if [ "${OS_VERSION}" = "Darwin" ]; then
+  find ./charts -type f -name README.md -exec sed -i '' -e '$ d' {} \;
+else
+  find ./charts -type f -name README.md -exec sed -i '$ d' {} \;
+fi
 
 find ./charts -type f -name README.md -maxdepth 2 -mindepth 2 -exec git add '{}' \;
 
 info "Done"
-
